### ISSUE TITLE
Strange behavior with chained number conversions

### ISSUE THREAD

**Issue by ShahriarKh** [persian-tools/persian-tools#103]
When using chained/multiple number conversions, the result isn't correct.
`converted = digitsFaToEn(digitsArToFa(nationalID));`

for example:
<pre dir="rtl">
0499370899 => 0499370899
۰۴۹۹۳۷۰۸۹۹ => 0499370899
٠٤٩٩٣٧٠٨٩٩ => ٠4٩٩٣٧٠٨٩٩ // incorrect
</pre>

I used different unicode ranges for arabic, but the only number considered as arabic is 4.

**Comment by ali-master** [comment]
It should be
```
converted = digitsArToFa(digitsFaToEn(nationalID));
```

**Comment by ShahriarKh** [comment]
> `converted = digitsArToFa(digitsFaToEn(nationalID));`

Doesn't work.

**Comment by ali-master** [comment]
Fixed and released v1.7.0. check it out and let me know if you have any other issues.

**Comment by ShahriarKh** [comment]
Thanks! It's better now; but still have problems.
For `٠١٢٣٤٥٦٧٨٩ ۰۱۲۳۴۵۶۷۸۹` I get:
```
ar to fa ۰۱۲۳۴۵۶۷۸۹ ۰۱۲۳۴۵۶۷۸۹ // correct
ar to en 0123456789 0123۴۵۶789 // X incorrect. Some Persian numbers are still treated as Arabic.
fa to en ٠١٢٣٤٥٦٧٨٩ 0123456789 // correct
```

**Comment by ali-master** [comment]
There are incorrect digits Unicode, please copy AR digits Unicodes in our test folder.

**Comment by ShahriarKh** [comment]
I'm sure the unicodes are correct.
`٠١٢٣٤٥٦٧٨٩` for Arabic ranging from `u0660` to `U0669`
`۰۱۲۳۴۵۶۷۸۹` for Persian (Extended Arabic-inidic) ranging from `u06F0` to `u06F9`

**Comment by ali-master** [comment]
@mediv0

**Comment by mediv0** [comment]
fixed #109
